
services:
  app:
    build:
      context: .
    ports:
      - "8001:80"
    environment:
      - ENVIRONMENT=dev
    volumes:
      - ./test_data:/app/input
      - ./test_data_output:/app/test_data_output
      - ./app.py:/app/app.py
