#!/bin/bash
set -e

echo Running black
uvx black src
echo Running isort
uvx isort src --profile black
echo Running ruff src
uvx ruff check --fix src
echo Running pyright src
uvx pyright src
echo Linting complete!
exit 0
