from pathlib import Path
from typing import Iterator, Protocol, Union, runtime_checkable

from virtual_fs import FSPath


@runtime_checkable
class PathLike(Protocol):
    """Protocol defining the interface that both Path and FSPath must implement."""

    def exists(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def mkdir(self, parents: bool = True, exist_ok: bool = True) -> None: ...
    def read_text(self, encoding: str = "utf-8") -> str: ...
    def write_text(self, data: str, encoding: str = "utf-8") -> None: ...
    def read_bytes(self) -> bytes: ...
    def write_bytes(self, data: bytes) -> None: ...

    @property
    def name(self) -> str: ...
    @property
    def stem(self) -> str: ...
    @property
    def suffix(self) -> str: ...
    @property
    def parent(self) -> "PathLike": ...

    def __truediv__(self, other: str) -> "PathLike": ...
    def __str__(self) -> str: ...
    def with_suffix(self, suffix: str) -> "PathLike": ...
    def with_name(self, name: str) -> "PathLike": ...
    def relative_to(self, other: "PathLike") -> "PathLike": ...
    def resolve(self) -> "PathLike": ...
    def glob(self, pattern: str) -> Iterator["PathLike"]: ...


# Type alias for paths that can be either local or remote
UniversalPath = Union[Path, FSPath]


def is_remote_path(path: UniversalPath) -> bool:
    """Check if a path is a remote FSPath."""
    return hasattr(path, "is_real_fs") and not path.is_real_fs()


def ensure_local_path(path: UniversalPath) -> Path:
    """Convert a UniversalPath to a local Path, downloading if necessary."""
    if isinstance(path, Path):
        return path
    else:
        # This would be handled by TempFileManager for actual files
        raise NotImplementedError("Use TempFileManager for remote file access")
